### ISSUE TITLE
Can I import your code to original repository?

### ISSUE THREAD

**Issue by dzavalishin** [ramonsmits/MqttUdpNet#8]
Hope it will help some people to use MQTT/UDP...

**Comment by ramonsmits** [comment]
Sure you can

**Comment by ramonsmits** [comment]
Could you add attribution and link back to this repo?

**Comment by dzavalishin** [comment]
Is it ok like this?

https://github.com/dzavalishin/mqtt_udp/blob/master/CONTRIBUTORS.md
